### ISSUE TITLE
你好 

### ISSUE THREAD

**Issue by cxk0703** [linklist2/PIAFusion_pytorch#1]
trans illum 只生成了文件夹 可以解决吗

**Comment by linklist2** [comment]
@cxk0703 请问是报错了？还是没有任何问题的执行完成后文件夹中没有图片？

**Comment by cxk0703** [comment]
是文件夹里没图片&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linklist2/PIAFusion_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月3日(星期天) 晚上11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linklist2/PIAFusion_pytorch] 你好  (Issue #1)





 
@cxk0703 请问是报错了？还是没有任何问题的执行完成后文件夹中没有图片？

**Comment by linklist2** [comment]
@cxk0703 加我qq吧：2273098543

**Comment by 122362** [comment]
Can you provide the function code for the evaluation metric after fusion? Thanks, expert
