### ISSUE TITLE
您好，请问可以问一下联系方式吗，我有一些问题想咨询

### ISSUE THREAD

**Issue by cheeenzq** [linklist2/PIAFusion_pytorch#2]
您好，请问可以问一下联系方式吗，我有一些问题想咨询，感谢。

**Comment by linklist2** [comment]
qq&nbsp; 2273098543


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月22日 11:05:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [linklist2/PIAFusion_pytorch] 您好，请问可以问一下联系方式吗，我有一些问题想咨询 (Issue #2)




 
您好，请问可以问一下联系方式吗，我有一些问题想咨询，感谢。

**Comment by linklist2** [comment]
@cheeenzq  qq:2273098543
