### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by songwenhao123** [linklist2/PIAFusion_pytorch#3]
PIAFusion_pytorch-master$ python trans_illum_data.py --h5_path 'datasets/data_illum.h5' --msrs_root_path 'datasets/cls_dataset'
usage: trans_illum_data.py [-h] [--h5_path DIR] [--cls_root_path DIR]
trans_illum_data.py: error: unrecognized arguments: --msrs_root_path datasets/cls_dataset

**Comment by linklist2** [comment]
please change msrs_root_path to cls_root_path

**Comment by linklist2** [comment]
I made a mistake in the readme file

**Comment by 122362** [comment]
Can you provide the function code for the evaluation metric after fusion? Thanks, expert
