### ISSUE TITLE
Unable to download the filesdata_illum.h5 and data_MSRS.h5

### ISSUE THREAD

**Issue by tom-kh** [linklist2/PIAFusion_pytorch#4]
Unable to download the filesdata_illum.h5 and data_MSRS.h5

**Comment by linklist2** [comment]
may not be able to access BaiduNetDisk in some places, I can try to send it to you through other methods, such as compressing it into volumes and sending it to you via email. Please provide your email number

**Comment by tom-kh** [comment]
yes sure thank you so much. My email address is patanaheen88@gmail.com

**Comment by tom-kh** [comment]
thank you so much for an earliest reply.
