### ISSUE TITLE
Loss do not fall when I training fusion network

### ISSUE THREAD

**Issue by SwordShiSan** [linklist2/PIAFusion_pytorch#9]
When I training fusion network,loss do not fall,The accuracy of the classification network can be reached almost 1
![image](https://github.com/linklist2/PIAFusion_pytorch/assets/88925431/7d09d2b7-6f0d-49cf-9bf2-dba92112f6d6)

**Comment by AtomComm** [comment]
请问您解决了这个问题嘛，我也遇到了loss不下降的情况
